### ISSUE TITLE
Evaluate Artillery vs Serverless Artillery

### ISSUE THREAD

**Issue by zanderhavgaard** [radon-h2020/cloudstash-characterization#3]
Should we use artillery or serverless artillery?
https://github.com/artilleryio/artillery
https://github.com/Nordstrom/serverless-artillery

**Comment by ChristofferNissen** [comment]
I have created Dockerfiles for both options on branch feature/artilliery for evaluation purposes. 

To me it seems that serverless art does lambda orchestration and takes care of scaling for us. It also seems that it can use a fully functional artilliery yml and do orchestration on top of that, so i would say we should just go with artillery for now. @zanderhavgaard, what do you think?
